[workspace]
members = [
  "installer",
  "dac_codec",
  "tezos_proto",
  "tezos_kernel",
  "michelson_vm",
  "tezos_node",
  "tezos_ctx",
  "sapling_proto",
  "sapling_kernel",
  "zcash_params"
]

[profile.release]
lto = true
opt-level = 'z'
panic = "abort"