[workspace]
members = [
  "kernel",
  "installer",
  "dac_codec",
  "tezos_l2",
  "tezos_vm",
  "tezos_node",
  "tezos_ctx",
  "michelson_derive",
  "michelson_interop"
]

[profile.release]
lto = true
opt-level = 'z'
panic = "abort"