# SPDX-FileCopyrightText: 2023 Baking Bad <hello@bakingbad.dev>
#
# SPDX-License-Identifier: MIT

version: "3.8"
services:
  operator:
    image: tot/operator:${TAG}
    command: run_node
    restart: "no"
    env_file:
      - .env
      # TAG e.g. tezos_kernel_v17.1
      # NETWORK e.g. nairobinet
      # ROLLUP_ADDRESS e.g. sr1...
      # OPERATOR_KEY e.g. unencrypted:edsk...
    ports:
      - 127.0.0.1:8932:8932
    networks:
      - internal

  facade:
    image: tot/facade:latest
    command: --endpoint http://operator:8932 --rpc-addr "0.0.0.0"
    restart: always
    ports:
      - 127.0.0.1:8732:8732
    networks:
      - internal

networks:
  internal: