version: "3.8"
services:
  operator:
    image: ghcr.io/baking-bad/tz-rollup-operator:${TAG:-mumbai}
    command: rollup-node
    restart: "no"
    env_file:
      - mumbai.env
      # ROLLUP_ADDRESS
      # OPERATOR_KEY
    ports:
      - 127.0.0.1:8932:8932
    networks:
      - internal

  facade:
    image: ghcr.io/baking-bad/tz-rollup-facade:${TAG:-mumbai}
    command: --endpoint http://operator:8932 --rpc-addr "0.0.0.0"
    restart: always
    ports:
      - 127.0.0.1:8732:8732
    networks:
      - internal

networks:
  internal: