[package]
name = "tez_kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
host = { git = "https://gitlab.com/tezos/kernel" }
debug = { git = "https://gitlab.com/tezos/kernel", default-features = false }
tezos_operation = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/dal-reveal-hash-encoding", package = "tezos-operation" }
tezos_core = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/dal-reveal-hash-encoding", package = "tezos-core" }
tezos_rpc = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/dal-reveal-hash-encoding", package = "tezos-rpc", default-features = false }
ed25519-dalek = "1.0.1"
num-traits = "*"
serde_json = "*"

[dev-dependencies]
mock_runtime = { git = "https://gitlab.com/tezos/kernel" }

[features]
default = []
repl = []