[package]
name = "tez_kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
proto = { path = "../proto" }
host = { git = "https://gitlab.com/tezos/kernel" }
derive_more = "0.99"
hex = "*"

[dev-dependencies]
mock_runtime = { git = "https://gitlab.com/tezos/kernel" }
hex = "*"