[package]
name = "tezos_kernel"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tezos_ctx = { path = "../tezos_ctx" }
tezos_proto = { path = "../tezos_proto" }
host = { git = "https://gitlab.com/tezos/kernel", rev = "417cdfbac778e96e1b9061b9f3b4517a6f1fa433" }
tezos_core = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/ibig-drop-in", package = "tezos-core", default-features = false }
tezos_operation = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/ibig-drop-in", package = "tezos-operation", default-features = false }

derive_more = "0.99"
hex = "*"

[dev-dependencies]
tezos_rpc = { git = "https://github.com/m-kus/tezos-rust-sdk", branch = "feat/ibig-drop-in", package = "tezos-rpc", default-features = false }
mock_runtime = { git = "https://gitlab.com/tezos/kernel", rev = "417cdfbac778e96e1b9061b9f3b4517a6f1fa433" }
hex = "*"