name: Build Sapling operator

on:
  push:
    branches:
      - 'master'
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Build and push docker images
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE_BASE: ${{ github.repository_owner }}
    outputs:
      operator: ${{ steps.meta-tezos-operator.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sapling operator tags & labels
        id: meta-sapling-operator
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_BASE }}/sapling-operator

      - name: Sapling operator build & push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: build/operator/Dockerfile
          build-args: |
            OCTEZ_TAG=v17.1
            OCTEZ_PROTO=PtNairob
            PACKAGE=sapling_kernel
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.meta-sapling-operator.outputs.tags }}
          labels: ${{ steps.meta-sapling-operator.outputs.labels }}
