name: Test

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run unit tests & try to build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo nextest run --tests

      - name: Publish results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          junit_files: "target/nextest/default/*.xml"

      - name: Install WASM tools
        run: make install

      - name: Build kernels
        run: make build
